### ISSUE TITLE
PyData Sphinx Theme searchbox design and accessibiity improvements

### ISSUE THREAD

**Issue by agriyakhetarpal** [algolia/sphinx-docsearch#33]
Hi there! I see that my earlier request (#14) was merged and a new release with the theme is out, but I wanted to highlight some potential areas of improvement and some workarounds that I have been using to add them:

<details>
<summary>1. Keyboard buttons are not correctly displayed</summary>

<img width="1089" alt="Screenshot 2024-05-28 at 3 33 47 PM" src="https://github.com/algolia/sphinx-docsearch/assets/74401230/7a8f936b-46ee-4f76-9f00-4ff36ca9cc86">

</details>

<details>
<summary>2. Not available on smaller-width (mobile) devices (because of "navbar_persistent" I guess)</summary>

<img width="350" alt="Screenshot 2024-05-28 at 3 36 49 PM" src="https://github.com/algolia/sphinx-docsearch/assets/74401230/86517d9d-e726-4618-a8df-96341ee9fcf4">

</details>

Some CSS fixes can be adopted for this:

```css
/* Do not add custom padding for keyboard buttons */

kbd:not(.compound) {
  padding: 0rem 0rem;
}

kbd.DocSearch-Commands-Key {
  border: 0;
  box-shadow: var(--docsearch-key-shadow);
  margin: 1px 5px 1px 0px;
  padding: inherit;
}
```

and some other improvements based on the styling for individual search results: https://github.com/pybamm-team/PyBaMM/blob/develop/docs/_static/pybamm.css#L107-L196. Not all of these are needed anymore, though, and this doesn't fix point 2, however...
