### ISSUE TITLE
Feat Request: sphinx-book-theme (pydata fork)

### ISSUE THREAD

**Issue by dylanh724** [algolia/sphinx-docsearch#62]
You guys support pydata, but sphinx-book-theme is a very popular fork (many enterprise folks use it, including _Unreal Engine_ docs) - would love to see official support.

Our docs for Xsolla Backend at https://docs.goxbe.io also use this theme.

Would love to see official support! In Sphinx 8, here's what we currently do to make it work:

1. Inject our own `js/algolia.js` that adds proper CTRL+K override support for the theme (may or may not be req'd now):

```html
// #########################################
// _static/js/algolia.js
// [This script should be loaded deferred]
// Initial template suggestion thanks from yafimvo @ 
// https://github.com/jupyter-book/jupyter-book/issues/1324#issuecomment-1512757574 
// #########################################

// On click, emulate CTRL+K to bring up search UI for both buttons
const searchButtons = document.querySelectorAll('.search-button__button');
searchButtons.forEach(button => {
	button.addEventListener('click', () => {
		console.log('[js/algolia.js] Clicked search btn -> emulating CTRL+K');
		const event = new KeyboardEvent('keydown', {
			key: 'k',
			ctrlKey: true,
			bubbles: true // Allows the event to propagate up through the DOM
		});
		document.dispatchEvent(event);
	});
});
```

2. CSS to adjust container z-index  and ensure the theme search is hidden:

```css
/* CSS autogen'd from SASS at sphinx-build time */

/*
Initial template suggestion from yafimvo @ 
https://github.com/jupyter-book/jupyter-book/issues/1324#issuecomment-1512757574 
*/

/* Hide the old search wrapper window when hitting Ctrl+K */
.search-button__wrapper, #search-input {
    display: none !important;
}

/* Make sure Algolia's search container is always on top */
.DocSearch.DocSearch-Container {
    z-index: 10000;
}
```

There's currently a breaking bug in this theme with my workarounds as of somewhat recently, so await this issue resolution 1st:

https://github.com/algolia/sphinx-docsearch/issues/60
